import {
  HospitalNode,
  BiomedicalDevice,
  InterHospitalLendingRequest,
  PatientEmergencySos,
  BiomedicalMaintenanceTicket,
  AppUser,
} from "../types";

export const INITIAL_HOSPITALS: HospitalNode[] = [
  {
    id: "hosp-aiims-delhi",
    name: "AIIMS New Delhi (Apex Trauma Centre)",
    category: "Government Tertiary",
    contactPhone: "+91 11 2658 8500",
    emergencyHelpline: "108 / 011-26593677",
    location: {
      lat: 28.5672,
      lng: 77.2100,
      address: "Sri Aurobindo Marg, Ansari Nagar",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110029",
    },
    beds: {
      general: { total: 1800, available: 142, reserved: 20, occupied: 1638 },
      icu: { total: 240, available: 18, reserved: 8, occupied: 214 },
      hdu: { total: 150, available: 22, reserved: 5, occupied: 123 },
      pediatric: { total: 120, available: 15, reserved: 3, occupied: 102 },
      ventilatorBeds: { total: 180, available: 14, reserved: 6, occupied: 160 },
    },
    oxygen: {
      liquidTankPercentage: 84,
      liquidTankCapacityLitres: 20000,
      dTypeCylindersAvailable: 110,
      dTypeCylindersTotal: 150,
      bTypeCylindersAvailable: 85,
      burnRateLitresPerHour: 420,
      estimatedHoursRemaining: 40,
      status: "NORMAL",
    },
    blood: {
      "A+": 48,
      "A-": 12,
      "B+": 62,
      "B-": 14,
      "AB+": 25,
      "AB-": 8,
      "O+": 85,
      "O-": 19,
      plasmaUnits: 94,
      plateletUnits: 58,
      lastUpdated: new Date().toISOString(),
    },
    ambulances: { total: 18, available: 7, dispatched: 11 },
    connectedSince: "2024-01-15",
    isNetworkVerified: true,
    equipmentList: [
      {
        id: "eq-aiims-vent-01",
        name: "Hamilton G5 ICU Ventilator",
        model: "Hamilton-G5-Pro",
        serialNumber: "HML-G5-2023-8821",
        category: "Ventilator",
        hospitalId: "hosp-aiims-delhi",
        hospitalName: "AIIMS New Delhi",
        wardLocation: "Trauma ICU - Bed 04",
        healthScore: 96,
        status: "OPTIMAL",
        isLendable: true,
        isCurrentlyLent: false,
        lastCalibrationDate: "2024-08-10",
        nextCalibrationDue: "2025-02-10",
        totalOperatingHours: 4120,
        telemetry: {
          powerStatus: "ON",
          voltageVolts: 228.4,
          oxygenPurityPercent: 99.2,
          temperatureCelsius: 36.8,
          batteryLevelPercent: 98,
          pressureKPa: 22.1,
          flowRateLpm: 34.5,
          lastTelemetrySync: new Date().toISOString(),
        },
      },
      {
        id: "eq-aiims-defib-02",
        name: "ZOLL R Series Defibrillator",
        model: "ZOLL-R-ALS",
        serialNumber: "ZOL-R9-4412",
        category: "Defibrillator",
        hospitalId: "hosp-aiims-delhi",
        hospitalName: "AIIMS New Delhi",
        wardLocation: "Emergency Resus Bay 01",
        healthScore: 92,
        status: "OPTIMAL",
        isLendable: true,
        isCurrentlyLent: false,
        lastCalibrationDate: "2024-07-20",
        nextCalibrationDue: "2025-01-20",
        totalOperatingHours: 1890,
        telemetry: {
          powerStatus: "STANDBY",
          voltageVolts: 230.1,
          temperatureCelsius: 24.2,
          batteryLevelPercent: 100,
          lastTelemetrySync: new Date().toISOString(),
        },
      },
      {
        id: "eq-aiims-dial-03",
        name: "Fresenius 5008S Dialysis Unit",
        model: "Fresenius-5008S",
        serialNumber: "FRS-5008-9901",
        category: "Dialysis Machine",
        hospitalId: "hosp-aiims-delhi",
        hospitalName: "AIIMS New Delhi",
        wardLocation: "Nephrology Ward - Unit 02",
        healthScore: 78,
        status: "ATTENTION_NEEDED",
        isLendable: false,
        isCurrentlyLent: false,
        lastCalibrationDate: "2024-05-12",
        nextCalibrationDue: "2024-11-12",
        totalOperatingHours: 7820,
        telemetry: {
          powerStatus: "ON",
          voltageVolts: 219.0,
          temperatureCelsius: 37.4,
          batteryLevelPercent: 82,
          lastTelemetrySync: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: "hosp-safdarjung",
    name: "Safdarjung Hospital & VMMC",
    category: "Government Tertiary",
    contactPhone: "+91 11 2616 5060",
    emergencyHelpline: "011-26707444",
    location: {
      lat: 28.5701,
      lng: 77.2078,
      address: "Ring Road, opposite AIIMS",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110029",
    },
    beds: {
      general: { total: 2200, available: 95, reserved: 15, occupied: 2090 },
      icu: { total: 180, available: 6, reserved: 4, occupied: 170 },
      hdu: { total: 120, available: 11, reserved: 2, occupied: 107 },
      pediatric: { total: 140, available: 18, reserved: 5, occupied: 117 },
      ventilatorBeds: { total: 130, available: 4, reserved: 2, occupied: 124 },
    },
    oxygen: {
      liquidTankPercentage: 54,
      liquidTankCapacityLitres: 15000,
      dTypeCylindersAvailable: 34,
      dTypeCylindersTotal: 90,
      bTypeCylindersAvailable: 40,
      burnRateLitresPerHour: 390,
      estimatedHoursRemaining: 21,
      status: "WARNING",
    },
    blood: {
      "A+": 32,
      "A-": 6,
      "B+": 44,
      "B-": 8,
      "AB+": 16,
      "AB-": 4,
      "O+": 41,
      "O-": 7,
      plasmaUnits: 45,
      plateletUnits: 28,
      lastUpdated: new Date().toISOString(),
    },
    ambulances: { total: 14, available: 4, dispatched: 10 },
    connectedSince: "2024-02-01",
    isNetworkVerified: true,
    equipmentList: [
      {
        id: "eq-safdar-vent-01",
        name: "Dräger Evita V300 Ventilator",
        model: "Dräger-V300",
        serialNumber: "DRG-EV3-5511",
        category: "Ventilator",
        hospitalId: "hosp-safdarjung",
        hospitalName: "Safdarjung Hospital",
        wardLocation: "Main Emergency ICU",
        healthScore: 68,
        status: "ATTENTION_NEEDED",
        isLendable: false,
        isCurrentlyLent: false,
        lastCalibrationDate: "2024-04-18",
        nextCalibrationDue: "2024-10-18",
        totalOperatingHours: 9240,
        telemetry: {
          powerStatus: "ON",
          voltageVolts: 221.5,
          oxygenPurityPercent: 94.1,
          temperatureCelsius: 38.1,
          batteryLevelPercent: 71,
          pressureKPa: 19.8,
          flowRateLpm: 31.0,
          lastTelemetrySync: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: "hosp-max-saket",
    name: "Max Super Speciality Hospital, Saket",
    category: "Private Multispecialty",
    contactPhone: "+91 11 2651 5050",
    emergencyHelpline: "011-40554055",
    location: {
      lat: 28.5273,
      lng: 77.2144,
      address: "1, 2, Press Enclave Marg, Saket",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110017",
    },
    beds: {
      general: { total: 550, available: 62, reserved: 10, occupied: 478 },
      icu: { total: 95, available: 16, reserved: 4, occupied: 75 },
      hdu: { total: 60, available: 14, reserved: 2, occupied: 44 },
      pediatric: { total: 40, available: 9, reserved: 1, occupied: 30 },
      ventilatorBeds: { total: 70, available: 12, reserved: 3, occupied: 55 },
    },
    oxygen: {
      liquidTankPercentage: 92,
      liquidTankCapacityLitres: 12000,
      dTypeCylindersAvailable: 80,
      dTypeCylindersTotal: 90,
      bTypeCylindersAvailable: 60,
      burnRateLitresPerHour: 180,
      estimatedHoursRemaining: 61,
      status: "NORMAL",
    },
    blood: {
      "A+": 40,
      "A-": 10,
      "B+": 55,
      "B-": 12,
      "AB+": 18,
      "AB-": 6,
      "O+": 60,
      "O-": 15,
      plasmaUnits: 72,
      plateletUnits: 40,
      lastUpdated: new Date().toISOString(),
    },
    ambulances: { total: 10, available: 6, dispatched: 4 },
    connectedSince: "2024-02-20",
    isNetworkVerified: true,
    equipmentList: [
      {
        id: "eq-max-vent-01",
        name: "Mindray SV300 Portable Ventilator",
        model: "Mindray-SV300",
        serialNumber: "MDR-SV-3091",
        category: "Ventilator",
        hospitalId: "hosp-max-saket",
        hospitalName: "Max Super Speciality Saket",
        wardLocation: "Critical Care Hub - Reserve",
        healthScore: 98,
        status: "OPTIMAL",
        isLendable: true,
        isCurrentlyLent: false,
        lastCalibrationDate: "2024-08-01",
        nextCalibrationDue: "2025-02-01",
        totalOperatingHours: 2300,
        telemetry: {
          powerStatus: "STANDBY",
          voltageVolts: 231.0,
          oxygenPurityPercent: 99.8,
          temperatureCelsius: 22.0,
          batteryLevelPercent: 100,
          lastTelemetrySync: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: "hosp-apollo-jasola",
    name: "Indraprastha Apollo Hospitals",
    category: "Private Multispecialty",
    contactPhone: "+91 11 2692 5858",
    emergencyHelpline: "1066",
    location: {
      lat: 28.5398,
      lng: 77.2842,
      address: "Sarita Vihar, Delhi Mathura Road",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110076",
    },
    beds: {
      general: { total: 710, available: 88, reserved: 12, occupied: 610 },
      icu: { total: 110, available: 19, reserved: 5, occupied: 86 },
      hdu: { total: 80, available: 16, reserved: 3, occupied: 61 },
      pediatric: { total: 50, available: 12, reserved: 2, occupied: 36 },
      ventilatorBeds: { total: 85, available: 15, reserved: 4, occupied: 66 },
    },
    oxygen: {
      liquidTankPercentage: 88,
      liquidTankCapacityLitres: 16000,
      dTypeCylindersAvailable: 95,
      dTypeCylindersTotal: 100,
      bTypeCylindersAvailable: 75,
      burnRateLitresPerHour: 220,
      estimatedHoursRemaining: 64,
      status: "NORMAL",
    },
    blood: {
      "A+": 50,
      "A-": 14,
      "B+": 60,
      "B-": 16,
      "AB+": 22,
      "AB-": 9,
      "O+": 78,
      "O-": 20,
      plasmaUnits: 88,
      plateletUnits: 52,
      lastUpdated: new Date().toISOString(),
    },
    ambulances: { total: 12, available: 8, dispatched: 4 },
    connectedSince: "2024-03-01",
    isNetworkVerified: true,
    equipmentList: [],
  },
  {
    id: "hosp-fortis-escorts",
    name: "Fortis Escorts Heart Institute, Okhla",
    category: "Private Multispecialty",
    contactPhone: "+91 11 4713 5000",
    emergencyHelpline: "011-47135000",
    location: {
      lat: 28.5601,
      lng: 77.2798,
      address: "Okhla Road, Sukhdev Vihar Metro",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110025",
    },
    beds: {
      general: { total: 310, available: 42, reserved: 5, occupied: 263 },
      icu: { total: 60, available: 9, reserved: 2, occupied: 49 },
      hdu: { total: 40, available: 8, reserved: 1, occupied: 31 },
      pediatric: { total: 25, available: 6, reserved: 1, occupied: 18 },
      ventilatorBeds: { total: 45, available: 7, reserved: 2, occupied: 36 },
    },
    oxygen: {
      liquidTankPercentage: 79,
      liquidTankCapacityLitres: 8000,
      dTypeCylindersAvailable: 50,
      dTypeCylindersTotal: 60,
      bTypeCylindersAvailable: 35,
      burnRateLitresPerHour: 110,
      estimatedHoursRemaining: 57,
      status: "NORMAL",
    },
    blood: {
      "A+": 28,
      "A-": 8,
      "B+": 38,
      "B-": 9,
      "AB+": 12,
      "AB-": 4,
      "O+": 45,
      "O-": 11,
      plasmaUnits: 40,
      plateletUnits: 25,
      lastUpdated: new Date().toISOString(),
    },
    ambulances: { total: 8, available: 5, dispatched: 3 },
    connectedSince: "2024-03-10",
    isNetworkVerified: true,
    equipmentList: [],
  },
];

export const INITIAL_REQUESTS: InterHospitalLendingRequest[] = [
  {
    id: "req-lend-9021",
    requestingHospitalId: "hosp-safdarjung",
    requestingHospitalName: "Safdarjung Hospital & VMMC",
    targetHospitalId: "hosp-max-saket",
    targetHospitalName: "Max Super Speciality Saket",
    itemType: "Ventilator",
    quantity: 3,
    priority: "CRITICAL_P1",
    clinicalReason: "Emergency Trauma Inflow: Mass casualty bus accident on Ring Road. All 4 backup ICU ventilators in active use.",
    requestedByDoctorName: "Dr. Rajesh Sharma (Chief ER Triage)",
    status: "IN_TRANSIT",
    transitOtp: "MED-8842",
    dispatchTime: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    estimatedArrivalMinutes: 12,
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: "req-lend-9022",
    requestingHospitalId: "hosp-aiims-delhi",
    requestingHospitalName: "AIIMS New Delhi",
    targetHospitalId: "hosp-apollo-jasola",
    targetHospitalName: "Indraprastha Apollo Hospitals",
    itemType: "Blood_Units",
    quantity: 8,
    priority: "URGENT_P2",
    clinicalReason: "Rare O-negative emergency supply needed for pediatric open heart surgery scheduled within 2 hours.",
    requestedByDoctorName: "Dr. Priya Sengupta (Transfusion Medicine)",
    status: "ACCEPTED",
    transitOtp: "MED-5190",
    estimatedArrivalMinutes: 28,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: "req-lend-9023",
    requestingHospitalId: "hosp-safdarjung",
    requestingHospitalName: "Safdarjung Hospital & VMMC",
    itemType: "Oxygen_Cylinders",
    quantity: 15,
    priority: "CRITICAL_P1",
    clinicalReason: "Type-D cylinder backup depletion due to high ward intake during seasonal respiratory surge.",
    requestedByDoctorName: "Dr. Vivek Mehra (Medical Superintendent)",
    status: "PENDING_MATCH",
    createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_SOS_REQUESTS: PatientEmergencySos[] = [
  {
    id: "sos-delhi-771",
    patientName: "Rohan Verma",
    contactPhone: "+91 98712 34567",
    abhaId: "91-4412-8821-0091",
    callerLatitude: 28.5492,
    callerLongitude: 77.2025,
    callerAddress: "Hauz Khas Market, New Delhi",
    emergencyType: "CARDIAC_ARREST",
    allocatedHospitalId: "hosp-aiims-delhi",
    allocatedHospitalName: "AIIMS New Delhi (Apex Trauma)",
    bedHoldToken: "ABHA-HOLD-992",
    bedHoldExpiresAt: new Date(Date.now() + 24 * 60 * 1000).toISOString(),
    ambulanceId: "AMB-DL-01-AIIMS",
    ambulanceDriverPhone: "+91 98110 54321",
    etaMinutes: 7,
    status: "BED_LOCKED_AMBULANCE_DISPATCHED",
    timestamp: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
  },
  {
    id: "sos-delhi-772",
    patientName: "Sunita Gupta",
    contactPhone: "+91 98109 87654",
    callerLatitude: 28.5290,
    callerLongitude: 77.2180,
    callerAddress: "Saket District Centre, New Delhi",
    emergencyType: "SEVERE_TRAUMA",
    allocatedHospitalId: "hosp-max-saket",
    allocatedHospitalName: "Max Super Speciality Saket",
    bedHoldToken: "ABHA-HOLD-814",
    bedHoldExpiresAt: new Date(Date.now() + 18 * 60 * 1000).toISOString(),
    ambulanceId: "AMB-DL-04-MAX",
    ambulanceDriverPhone: "+91 97118 90123",
    etaMinutes: 11,
    status: "EN_ROUTE",
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_MAINTENANCE_TICKETS: BiomedicalMaintenanceTicket[] = [
  {
    id: "tkt-bme-101",
    deviceId: "eq-safdar-vent-01",
    deviceName: "Dräger Evita V300 Ventilator",
    hospitalId: "hosp-safdarjung",
    hospitalName: "Safdarjung Hospital",
    wardLocation: "Main Emergency ICU",
    issueDescription: "IoT Telemetry Warning: Oxygen sensor cell degradation detected (FiO2 output measured 94.1% vs target 99.5%). Pressure relief valve calibration due.",
    severity: "HIGH",
    status: "IN_PROGRESS",
    assignedEngineerId: "eng-kunal-07",
    assignedEngineerName: "Er. Kunal Singhania (Senior BME)",
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    notes: [
      "Auto-triggered by MedGrid IoT Telemetry sensor agent.",
      "Replacement O2 fuel cell sensor kit #DRG-992 dispatched from Central BME store.",
    ],
  },
  {
    id: "tkt-bme-102",
    deviceId: "eq-aiims-dial-03",
    deviceName: "Fresenius 5008S Dialysis Unit",
    hospitalId: "hosp-aiims-delhi",
    hospitalName: "AIIMS New Delhi",
    wardLocation: "Nephrology Ward - Unit 02",
    issueDescription: "Preventive Calibration Overdue (NABH Standard 4.2). Heparin pump volumetric verification required.",
    severity: "MEDIUM",
    status: "OPEN",
    createdAt: new Date(Date.now() - 420 * 60 * 1000).toISOString(),
    notes: ["Scheduled for biomedical engineer routine inspection round."],
  },
];

export const DEMO_USERS: AppUser[] = [
  {
    id: "user-patient-01",
    name: "Amit Patel (Citizen)",
    email: "amit.patel@gmail.com",
    phone: "+91 98765 43210",
    role: "patient",
    abhaId: "91-8843-1209-7741",
    bloodGroup: "O+",
    emergencyContactName: "Pooja Patel (Spouse)",
    emergencyContactPhone: "+91 98765 43211",
    currentAddress: "B-42, South Extension Part II, New Delhi",
    createdAt: "2024-01-01",
  },
  {
    id: "user-doctor-01",
    name: "Dr. Ananya Roy, MD",
    email: "dr.ananya@safdarjung.gov.in",
    phone: "+91 98112 34890",
    role: "doctor",
    licenseNumber: "DMC-REG-2016-89421",
    hospitalId: "hosp-safdarjung",
    hospitalName: "Safdarjung Hospital & VMMC",
    department: "Emergency & Critical Care Medicine",
    specialization: "Trauma & Resuscitation Specialist",
    isOnDuty: true,
    createdAt: "2024-01-10",
  },
  {
    id: "user-coordinator-01",
    name: "Er. Vikram Malhotra",
    email: "vikram.bme@aiims.edu",
    phone: "+91 98223 90124",
    role: "coordinator",
    instituteId: "hosp-aiims-delhi",
    instituteName: "AIIMS New Delhi - Central BME Directorate",
    department: "Biomedical Engineering",
    assignedZones: ["Delhi Central", "Delhi South", "NCR West"],
    badgeId: "BME-AIIMS-GOLD-09",
    createdAt: "2024-01-05",
  },
];
